// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SquadController from "./squad_controller"
application.register("squad", SquadController)

import LocationPickerController from "./location_picker_controller"
application.register("location-picker", LocationPickerController)

import ClubsMapController from "./clubs_map_controller"
application.register("clubs-map", ClubsMapController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)