// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SquadController from "./squad_controller"
application.register("squad", SquadController)

import LocationPickerController from "./location_picker_controller"
application.register("location-picker", LocationPickerController)

import ClubsMapController from "./clubs_map_controller"
application.register("clubs-map", ClubsMapController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import ClubQuestionsController from "./club_questions_controller"
application.register("club-questions", ClubQuestionsController)

import MembershipQuestionFormController from "./membership_question_form_controller"
application.register("membership-question-form", MembershipQuestionFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MembershipsSelectionController from "./memberships_selection_controller"
application.register("memberships-selection", MembershipsSelectionController)

import MembershipStartController from "./membership_start_controller"
application.register("membership-start", MembershipStartController)

import SaIdController from "./sa_id_controller"
application.register("sa-id", SaIdController)

import PaymentMethodController from "./payment_method_controller"
application.register("payment-method", PaymentMethodController)

import StaggeredPaymentPlanController from "./staggered_payment_plan_controller"
application.register("staggered-payment-plan", StaggeredPaymentPlanController)

import PaymentPlanSelectorController from "./payment_plan_selector_controller"
application.register("payment-plan-selector", PaymentPlanSelectorController)

import ClubThemeColorController from "./club_theme_color_controller"
application.register("club-theme-color", ClubThemeColorController)

import CountryCodeSelectorController from "./country_code_selector_controller"
application.register("country-code-selector", CountryCodeSelectorController)

import MobileNumberController from "./mobile_number_controller"
application.register("mobile-number", MobileNumberController)
