# Domain Settings
base_domain: <%= ENV.fetch("BASE_DOMAIN") %>
base_url: <%= ENV.fetch("BASE_URL") %>

# Bunny CDN/Storage (used by ActiveStorage Bunny service)
bunny:
  access_key: <%= ENV.fetch("BUNNY_ACCESS_KEY") %>
  api_key: <%= ENV.fetch("BUNNY_API_KEY") %>
  storage_zone: <%= ENV.fetch("BUNNY_STORAGE_ZONE") %>
  region: <%= ENV.fetch("BUNNY_REGION", "") %>
  cdn: <%= ENV.fetch("BUNNY_CDN_ENDPOINT") %>

paygate:
  pay_host:
    endpoint: <%= ENV.fetch("PAYGATE_PAY_HOST_ENDPOINT", "https://secure.paygate.co.za/payhost/process.trans") %>
    merchant_id: <%= ENV.fetch("PAYGATE_MERCHANT_ID") %>
    password: <%= ENV.fetch("PAYGATE_PASSWORD") %>
    return_url: <%= ENV.fetch("PAYGATE_RETURN_URL") %>
    notify_url: <%= ENV.fetch("PAYGATE_NOTIFY_URL") %>

google:
  places_api_key: <%= ENV.fetch("GOOGLE_PLACES_API_KEY", "") %>

whatsapp:
  access_token: <%= ENV.fetch("WHATSAPP_ACCESS_TOKEN", nil) %>
  sender_id: <%= ENV.fetch("WHATSAPP_SENDER_ID", nil) %>
  business_id: <%= ENV.fetch("WHATSAPP_BUSINESS_ID", nil) %>
  otp_template_id: <%= ENV.fetch("WHATSAPP_OTP_TEMPLATE_ID", nil) %>
  order_confirmation_template_id: <%= ENV.fetch("WHATSAPP_ORDER_CONFIRMATION_TEMPLATE_ID", nil) %>
